INSERT INTO god_voice.volume(volume_number, volume_name, volume_short, chapter_amount, version, create_date, update_date) VALUES ('1', 'Księga Rodzaju', 'Rdz', '50', '1', now(), now());
INSERT INTO god_voice.volume(volume_number, volume_name, volume_short, chapter_amount, version, create_date, update_date) VALUES ('2', 'Księga Wyjścia', 'Wj', '40', '1', now(), now());
INSERT INTO god_voice.volume(volume_number, volume_name, volume_short, chapter_amount, version, create_date, update_date) VALUES ('3', 'Księga Kapłańska', 'Kpł', '27', '1', now(), now());
INSERT INTO god_voice.volume(volume_number, volume_name, volume_short, chapter_amount, version, create_date, update_date) VALUES ('4', 'Księga Liczb', 'Lb', '36', '1', now(), now());
INSERT INTO god_voice.volume(volume_number, volume_name, volume_short, chapter_amount, version, create_date, update_date) VALUES ('5', 'Księga Powtórzonego Prawa', 'Pwp', '34', '1', now(), now());
INSERT INTO god_voice.volume(volume_number, volume_name, volume_short, chapter_amount, version, create_date, update_date) VALUES ('6', 'Księga Jozuego', 'Joz', '24', '1', now(), now());
INSERT INTO god_voice.volume(volume_number, volume_name, volume_short, chapter_amount, version, create_date, update_date) VALUES ('7', 'Księga Sędziów', 'Sdz', '21', '1', now(), now());
INSERT INTO god_voice.volume(volume_number, volume_name, volume_short, chapter_amount, version, create_date, update_date) VALUES ('8', 'Księga Rut', 'Rt', '4', '1', now(), now());
INSERT INTO god_voice.volume(volume_number, volume_name, volume_short, chapter_amount, version, create_date, update_date) VALUES ('9', '1 Księga Samuela', '1 Sm', '21', '1', now(), now());
INSERT INTO god_voice.volume(volume_number, volume_name, volume_short, chapter_amount, version, create_date, update_date) VALUES ('10', '2 Księga Samuela', '2 Sm', '24', '1', now(), now());
INSERT INTO god_voice.volume(volume_number, volume_name, volume_short, chapter_amount, version, create_date, update_date) VALUES ('11', '1Księga Królewska', '1 Krl', '22', '1', now(), now());
INSERT INTO god_voice.volume(volume_number, volume_name, volume_short, chapter_amount, version, create_date, update_date) VALUES ('12', '2Księga Królewska', '2 Krl', '25', '1', now(), now());
INSERT INTO god_voice.volume(volume_number, volume_name, volume_short, chapter_amount, version, create_date, update_date) VALUES ('13', '1Księga Kronik', '1 Krn', '29', '1', now(), now());
INSERT INTO god_voice.volume(volume_number, volume_name, volume_short, chapter_amount, version, create_date, update_date) VALUES ('14', '2Księga Kronik', '2 Krn', '36', '1', now(), now());
INSERT INTO god_voice.volume(volume_number, volume_name, volume_short, chapter_amount, version, create_date, update_date) VALUES ('15', 'Księga Ezdrasza', 'Ezd', '10', '1', now(), now());
INSERT INTO god_voice.volume(volume_number, volume_name, volume_short, chapter_amount, version, create_date, update_date) VALUES ('16', 'Księga Nehemiasza', 'Ne', '13', '1', now(), now());
INSERT INTO god_voice.volume(volume_number, volume_name, volume_short, chapter_amount, version, create_date, update_date) VALUES ('17', 'Księga Tobiasza', 'Tb', '14', '1', now(), now());
INSERT INTO god_voice.volume(volume_number, volume_name, volume_short, chapter_amount, version, create_date, update_date) VALUES ('18', 'Księga Judyty', 'Jdt', '16', '1', now(), now());
INSERT INTO god_voice.volume(volume_number, volume_name, volume_short, chapter_amount, version, create_date, update_date) VALUES ('19', 'Księga Estery', 'Est', '10', '1', now(), now());
INSERT INTO god_voice.volume(volume_number, volume_name, volume_short, chapter_amount, version, create_date, update_date) VALUES ('20', '1 Księga Machabejska', '1 Mch', '16', '1', now(), now());
INSERT INTO god_voice.volume(volume_number, volume_name, volume_short, chapter_amount, version, create_date, update_date) VALUES ('21', '2 Księga Machabejska', '2 Mch', '15', '1', now(), now());
INSERT INTO god_voice.volume(volume_number, volume_name, volume_short, chapter_amount, version, create_date, update_date) VALUES ('22', 'Księga Hioba', 'Hi', '42', '1', now(), now());
INSERT INTO god_voice.volume(volume_number, volume_name, volume_short, chapter_amount, version, create_date, update_date) VALUES ('23', 'Księga Psalmów', 'Ps', '150', '1', now(), now());
INSERT INTO god_voice.volume(volume_number, volume_name, volume_short, chapter_amount, version, create_date, update_date) VALUES ('24', 'Księga Przysłów', 'Prz', '31', '1', now(), now());
INSERT INTO god_voice.volume(volume_number, volume_name, volume_short, chapter_amount, version, create_date, update_date) VALUES ('25', 'Księga Koheleta', 'Koh', '12', '1', now(), now());
INSERT INTO god_voice.volume(volume_number, volume_name, volume_short, chapter_amount, version, create_date, update_date) VALUES ('26', 'Pieśń nad Pieśniami', 'Pnp', '8', '1', now(), now());
INSERT INTO god_voice.volume(volume_number, volume_name, volume_short, chapter_amount, version, create_date, update_date) VALUES ('27', 'Księga Mądrości', 'Mdr', '19', '1', now(), now());
INSERT INTO god_voice.volume(volume_number, volume_name, volume_short, chapter_amount, version, create_date, update_date) VALUES ('28', 'Mądrość Syracha', 'Syr', '51', '1', now(), now());
INSERT INTO god_voice.volume(volume_number, volume_name, volume_short, chapter_amount, version, create_date, update_date) VALUES ('29', 'Księga Izajasza', 'Iz', '66', '1', now(), now());
INSERT INTO god_voice.volume(volume_number, volume_name, volume_short, chapter_amount, version, create_date, update_date) VALUES ('30', 'Księga Jeremiasza', 'Jr', '52', '1', now(), now());
INSERT INTO god_voice.volume(volume_number, volume_name, volume_short, chapter_amount, version, create_date, update_date) VALUES ('31', 'Lamentacje', 'Lm', '5', '1', now(), now());
INSERT INTO god_voice.volume(volume_number, volume_name, volume_short, chapter_amount, version, create_date, update_date) VALUES ('32', 'Księga Barucha', 'Ba', '6', '1', now(), now());
INSERT INTO god_voice.volume(volume_number, volume_name, volume_short, chapter_amount, version, create_date, update_date) VALUES ('33', 'Księga Ezechiela', 'Ez', '48', '1', now(), now());
INSERT INTO god_voice.volume(volume_number, volume_name, volume_short, chapter_amount, version, create_date, update_date) VALUES ('34', 'Księga Daniela', 'Dn', '14', '1', now(), now());
INSERT INTO god_voice.volume(volume_number, volume_name, volume_short, chapter_amount, version, create_date, update_date) VALUES ('35', 'Księga Ozeasza', 'Oz', '14', '1', now(), now());
INSERT INTO god_voice.volume(volume_number, volume_name, volume_short, chapter_amount, version, create_date, update_date) VALUES ('36', 'Księga Joela', 'Jl', '4', '1', now(), now());
INSERT INTO god_voice.volume(volume_number, volume_name, volume_short, chapter_amount, version, create_date, update_date) VALUES ('37', 'Księga Amosa', 'Am', '9', '1', now(), now());
INSERT INTO god_voice.volume(volume_number, volume_name, volume_short, chapter_amount, version, create_date, update_date) VALUES ('38', 'Księga Abdiasza', 'Ab', '1', '1', now(), now());
INSERT INTO god_voice.volume(volume_number, volume_name, volume_short, chapter_amount, version, create_date, update_date) VALUES ('39', 'Księga Jonasza', 'Jon', '4', '1', now(), now());
INSERT INTO god_voice.volume(volume_number, volume_name, volume_short, chapter_amount, version, create_date, update_date) VALUES ('40', 'Księga Micheasza', 'Mi', '7', '1', now(), now());
INSERT INTO god_voice.volume(volume_number, volume_name, volume_short, chapter_amount, version, create_date, update_date) VALUES ('41', 'Księga Nahuma', 'Na', '3', '1', now(), now());
INSERT INTO god_voice.volume(volume_number, volume_name, volume_short, chapter_amount, version, create_date, update_date) VALUES ('42', 'Księga Habakuka', 'Ha', '3', '1', now(), now());
INSERT INTO god_voice.volume(volume_number, volume_name, volume_short, chapter_amount, version, create_date, update_date) VALUES ('43', 'Księga Sofoniasza', 'So', '3', '1', now(), now());
INSERT INTO god_voice.volume(volume_number, volume_name, volume_short, chapter_amount, version, create_date, update_date) VALUES ('44', 'Księga Aggeusza', 'Ag', '2', '1', now(), now());
INSERT INTO god_voice.volume(volume_number, volume_name, volume_short, chapter_amount, version, create_date, update_date) VALUES ('45', 'Księga Zachariasza', 'Za', '14', '1', now(), now());
INSERT INTO god_voice.volume(volume_number, volume_name, volume_short, chapter_amount, version, create_date, update_date) VALUES ('46', 'Księga Malachiasza', 'Ml', '3', '1', now(), now());
INSERT INTO god_voice.volume(volume_number, volume_name, volume_short, chapter_amount, version, create_date, update_date) VALUES ('47', 'Ewangelia Mateusza', 'Mt', '28', '1', now(), now());
INSERT INTO god_voice.volume(volume_number, volume_name, volume_short, chapter_amount, version, create_date, update_date) VALUES ('48', 'Ewangelia Marka', 'Mk', '16', '1', now(), now());
INSERT INTO god_voice.volume(volume_number, volume_name, volume_short, chapter_amount, version, create_date, update_date) VALUES ('49', 'Ewangelia Łukasza', 'Łk', '24', '1', now(), now());
INSERT INTO god_voice.volume(volume_number, volume_name, volume_short, chapter_amount, version, create_date, update_date) VALUES ('50', 'Ewangelia Jana', 'J', '21', '1', now(), now());
INSERT INTO god_voice.volume(volume_number, volume_name, volume_short, chapter_amount, version, create_date, update_date) VALUES ('51', 'Dzieje Apostolskie', 'Dz', '28', '1', now(), now());
INSERT INTO god_voice.volume(volume_number, volume_name, volume_short, chapter_amount, version, create_date, update_date) VALUES ('52', 'List do Rzymian', 'Rz', '16', '1', now(), now());
INSERT INTO god_voice.volume(volume_number, volume_name, volume_short, chapter_amount, version, create_date, update_date) VALUES ('53', '1 List do Koryntian', '1 Kor', '16', '1', now(), now());
INSERT INTO god_voice.volume(volume_number, volume_name, volume_short, chapter_amount, version, create_date, update_date) VALUES ('54', '2 List do Koryntian', '2 Kor', '13', '1', now(), now());
INSERT INTO god_voice.volume(volume_number, volume_name, volume_short, chapter_amount, version, create_date, update_date) VALUES ('55', 'List do Galatów', 'Ga', '6', '1', now(), now());
INSERT INTO god_voice.volume(volume_number, volume_name, volume_short, chapter_amount, version, create_date, update_date) VALUES ('56', 'List do Efezjan', 'Ef', '6', '1', now(), now());
INSERT INTO god_voice.volume(volume_number, volume_name, volume_short, chapter_amount, version, create_date, update_date) VALUES ('57', 'List do Filipian', 'Flp', '4', '1', now(), now());
INSERT INTO god_voice.volume(volume_number, volume_name, volume_short, chapter_amount, version, create_date, update_date) VALUES ('58', 'List do Kolosan', 'Kol', '4', '1', now(), now());
INSERT INTO god_voice.volume(volume_number, volume_name, volume_short, chapter_amount, version, create_date, update_date) VALUES ('59', '1 List do Tesaloniczan', '1 Tes', '5', '1', now(), now());
INSERT INTO god_voice.volume(volume_number, volume_name, volume_short, chapter_amount, version, create_date, update_date) VALUES ('60', '2 List do Tesaloniczan', '2 Tes', '3', '1', now(), now());
INSERT INTO god_voice.volume(volume_number, volume_name, volume_short, chapter_amount, version, create_date, update_date) VALUES ('61', '1 List do Tymoteusza', '1 Tm', '6', '1', now(), now());
INSERT INTO god_voice.volume(volume_number, volume_name, volume_short, chapter_amount, version, create_date, update_date) VALUES ('62', '2 List do Tymoteusza', '2 Tm', '4', '1', now(), now());
INSERT INTO god_voice.volume(volume_number, volume_name, volume_short, chapter_amount, version, create_date, update_date) VALUES ('63', 'List do Tytusa', 'Tt', '3', '1', now(), now());
INSERT INTO god_voice.volume(volume_number, volume_name, volume_short, chapter_amount, version, create_date, update_date) VALUES ('64', 'List do Filemona', 'Flm', '1', '1', now(), now());
INSERT INTO god_voice.volume(volume_number, volume_name, volume_short, chapter_amount, version, create_date, update_date) VALUES ('65', 'List do Hebrajczyków', 'Hbr', '13', '1', now(), now());
INSERT INTO god_voice.volume(volume_number, volume_name, volume_short, chapter_amount, version, create_date, update_date) VALUES ('66', 'List Jakuba', 'Jk', '5', '1', now(), now());
INSERT INTO god_voice.volume(volume_number, volume_name, volume_short, chapter_amount, version, create_date, update_date) VALUES ('67', '1 List Piotra', '1 P', '5', '1', now(), now());
INSERT INTO god_voice.volume(volume_number, volume_name, volume_short, chapter_amount, version, create_date, update_date) VALUES ('68', '2 List Piotra', '2 P', '3', '1', now(), now());
INSERT INTO god_voice.volume(volume_number, volume_name, volume_short, chapter_amount, version, create_date, update_date) VALUES ('69', '1 List Jana', '1 J', '5', '1', now(), now());
INSERT INTO god_voice.volume(volume_number, volume_name, volume_short, chapter_amount, version, create_date, update_date) VALUES ('70', '2 List Jana', '2 J', '1', '1', now(), now());
INSERT INTO god_voice.volume(volume_number, volume_name, volume_short, chapter_amount, version, create_date, update_date) VALUES ('71', '3 List Jana', '3 J', '1', '1', now(), now());
INSERT INTO god_voice.volume(volume_number, volume_name, volume_short, chapter_amount, version, create_date, update_date) VALUES ('72', 'List Judy', 'Jud', '1', '1', now(), now());
INSERT INTO god_voice.volume(volume_number, volume_name, volume_short, chapter_amount, version, create_date, update_date) VALUES ('73', 'Apokalipsa św. Jana', 'Ap', '22', '1', now(), now());
