INSERT INTO god_voice.chapter(volume_no, chapter, verses, version, create_date, update_date) VALUES ('1', '1', '31', '1', now(), now());
INSERT INTO god_voice.chapter(volume_no, chapter, verses, version, create_date, update_date) VALUES ('1', '2', '25', '1', now(), now());
INSERT INTO god_voice.chapter(volume_no, chapter, verses, version, create_date, update_date) VALUES ('1', '3', '24', '1', now(), now());
INSERT INTO god_voice.chapter(volume_no, chapter, verses, version, create_date, update_date) VALUES ('1', '4', '26', '1', now(), now());
INSERT INTO god_voice.chapter(volume_no, chapter, verses, version, create_date, update_date) VALUES ('1', '5', '32', '1', now(), now());
INSERT INTO god_voice.chapter(volume_no, chapter, verses, version, create_date, update_date) VALUES ('1', '6', '22', '1', now(), now());
INSERT INTO god_voice.chapter(volume_no, chapter, verses, version, create_date, update_date) VALUES ('1', '7', '24', '1', now(), now());
INSERT INTO god_voice.chapter(volume_no, chapter, verses, version, create_date, update_date) VALUES ('1', '8', '22', '1', now(), now());
INSERT INTO god_voice.chapter(volume_no, chapter, verses, version, create_date, update_date) VALUES ('1', '9', '29', '1', now(), now());
INSERT INTO god_voice.chapter(volume_no, chapter, verses, version, create_date, update_date) VALUES ('1', '10', '32', '1', now(), now());
INSERT INTO god_voice.chapter(volume_no, chapter, verses, version, create_date, update_date) VALUES ('1', '11', '32', '1', now(), now());
INSERT INTO god_voice.chapter(volume_no, chapter, verses, version, create_date, update_date) VALUES ('1', '12', '20', '1', now(), now());
INSERT INTO god_voice.chapter(volume_no, chapter, verses, version, create_date, update_date) VALUES ('1', '13', '18', '1', now(), now());
INSERT INTO god_voice.chapter(volume_no, chapter, verses, version, create_date, update_date) VALUES ('1', '14', '24', '1', now(), now());
INSERT INTO god_voice.chapter(volume_no, chapter, verses, version, create_date, update_date) VALUES ('1', '15', '21', '1', now(), now());
INSERT INTO god_voice.chapter(volume_no, chapter, verses, version, create_date, update_date) VALUES ('1', '16', '16', '1', now(), now());
INSERT INTO god_voice.chapter(volume_no, chapter, verses, version, create_date, update_date) VALUES ('1', '17', '27', '1', now(), now());
INSERT INTO god_voice.chapter(volume_no, chapter, verses, version, create_date, update_date) VALUES ('1', '18', '33', '1', now(), now());
INSERT INTO god_voice.chapter(volume_no, chapter, verses, version, create_date, update_date) VALUES ('1', '19', '38', '1', now(), now());
INSERT INTO god_voice.chapter(volume_no, chapter, verses, version, create_date, update_date) VALUES ('1', '20', '18', '1', now(), now());
INSERT INTO god_voice.chapter(volume_no, chapter, verses, version, create_date, update_date) VALUES ('1', '21', '34', '1', now(), now());
INSERT INTO god_voice.chapter(volume_no, chapter, verses, version, create_date, update_date) VALUES ('1', '22', '24', '1', now(), now());
INSERT INTO god_voice.chapter(volume_no, chapter, verses, version, create_date, update_date) VALUES ('1', '23', '20', '1', now(), now());
INSERT INTO god_voice.chapter(volume_no, chapter, verses, version, create_date, update_date) VALUES ('1', '24', '67', '1', now(), now());
INSERT INTO god_voice.chapter(volume_no, chapter, verses, version, create_date, update_date) VALUES ('1', '25', '34', '1', now(), now());
INSERT INTO god_voice.chapter(volume_no, chapter, verses, version, create_date, update_date) VALUES ('1', '26', '35', '1', now(), now());
INSERT INTO god_voice.chapter(volume_no, chapter, verses, version, create_date, update_date) VALUES ('1', '27', '46', '1', now(), now());
INSERT INTO god_voice.chapter(volume_no, chapter, verses, version, create_date, update_date) VALUES ('1', '28', '22', '1', now(), now());
INSERT INTO god_voice.chapter(volume_no, chapter, verses, version, create_date, update_date) VALUES ('1', '29', '35', '1', now(), now());
INSERT INTO god_voice.chapter(volume_no, chapter, verses, version, create_date, update_date) VALUES ('1', '30', '43', '1', now(), now());
INSERT INTO god_voice.chapter(volume_no, chapter, verses, version, create_date, update_date) VALUES ('1', '31', '54', '1', now(), now());
INSERT INTO god_voice.chapter(volume_no, chapter, verses, version, create_date, update_date) VALUES ('1', '32', '33', '1', now(), now());
INSERT INTO god_voice.chapter(volume_no, chapter, verses, version, create_date, update_date) VALUES ('1', '33', '20', '1', now(), now());
INSERT INTO god_voice.chapter(volume_no, chapter, verses, version, create_date, update_date) VALUES ('1', '34', '31', '1', now(), now());
INSERT INTO god_voice.chapter(volume_no, chapter, verses, version, create_date, update_date) VALUES ('1', '35', '29', '1', now(), now());
INSERT INTO god_voice.chapter(volume_no, chapter, verses, version, create_date, update_date) VALUES ('1', '36', '43', '1', now(), now());
INSERT INTO god_voice.chapter(volume_no, chapter, verses, version, create_date, update_date) VALUES ('1', '37', '36', '1', now(), now());
INSERT INTO god_voice.chapter(volume_no, chapter, verses, version, create_date, update_date) VALUES ('1', '38', '30', '1', now(), now());
INSERT INTO god_voice.chapter(volume_no, chapter, verses, version, create_date, update_date) VALUES ('1', '39', '23', '1', now(), now());
INSERT INTO god_voice.chapter(volume_no, chapter, verses, version, create_date, update_date) VALUES ('1', '40', '23', '1', now(), now());
INSERT INTO god_voice.chapter(volume_no, chapter, verses, version, create_date, update_date) VALUES ('1', '41', '57', '1', now(), now());
INSERT INTO god_voice.chapter(volume_no, chapter, verses, version, create_date, update_date) VALUES ('1', '42', '38', '1', now(), now());
INSERT INTO god_voice.chapter(volume_no, chapter, verses, version, create_date, update_date) VALUES ('1', '43', '34', '1', now(), now());
INSERT INTO god_voice.chapter(volume_no, chapter, verses, version, create_date, update_date) VALUES ('1', '44', '34', '1', now(), now());
INSERT INTO god_voice.chapter(volume_no, chapter, verses, version, create_date, update_date) VALUES ('1', '45', '28', '1', now(), now());
INSERT INTO god_voice.chapter(volume_no, chapter, verses, version, create_date, update_date) VALUES ('1', '46', '34', '1', now(), now());
INSERT INTO god_voice.chapter(volume_no, chapter, verses, version, create_date, update_date) VALUES ('1', '47', '31', '1', now(), now());
INSERT INTO god_voice.chapter(volume_no, chapter, verses, version, create_date, update_date) VALUES ('1', '48', '22', '1', now(), now());
INSERT INTO god_voice.chapter(volume_no, chapter, verses, version, create_date, update_date) VALUES ('1', '49', '33', '1', now(), now());
INSERT INTO god_voice.chapter(volume_no, chapter, verses, version, create_date, update_date) VALUES ('1', '50', '26', '1', now(), now());

-- ========================================

-- USE god_voice;
-- select * from volume;
-- select * from chapter;
-- select * from volume v join chapter c ON (v.volume_number = c.volume_no);
-- SELECT v.chapter_amount FROM volume v WHERE v.id = 1;
-- SELECT v.chapter_amount FROM volume v WHERE v.volume_number = 1;
-- select * from volume v join chapter c ON (v.volume_number = c.volume_no) where v.volume_number = 1 AND c.chapter = 18;
